### ISSUE TITLE
refactor kaizen command line

### ISSUE THREAD

**Issue by ahlumin** [PortalNetwork/kaizen-cli#42]
As KAIZEN CLI is integrating more services and functions, it is necessary to restructure its codebase. This issue is a list of things that has been updated and to be updated.

__Below were completed in https://github.com/PortalNetwork/kaizen-cli/pull/43__
- [x] deprecate 'kaizen init'.
- [x] deprecate 'kaizen plugin', and replace it with 'kaizen add --package'.
- [x] new Bluzelle integrated library.
- [x] new processing spinner animation

__To be updated__
- [ ] integrate with NOIA sdk
- [ ] update document

**Comment by PhyrexTsai** [comment]
Upgrade to new plugin integration method, issue close
