### ISSUE TITLE
user authorized mechanism

### ISSUE THREAD

**Issue by ahlumin** [PortalNetwork/kaizen-cli#60]
In order to support the KAIZEN manager, KAIZEN CLI should have the user authorized mechanism to log in and log out KAIZEN manager.

**Comment by PhyrexTsai** [comment]
The KAIZEN CLI authorized only need for some function, not all of the command are needed.
So please consider about how to separate this part to add in KAIZEN CLI

**Comment by ahlumin** [comment]
#63
